# Generated by Django 4.2.3 on 2023-07-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
