# Generated by Django 4.2.3 on 2023-07-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_alter_product_description_alter_product_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, to='ecommerce_app.tag'),
        ),
    ]
