# Generated by Django 4.2.3 on 2023-07-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture_url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
